import os
import sys
from unittest.mock import patch

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))

from pcluster_core import (
    PClusterMakerError,
    _validate_queue_name,
    _validate_instance_types,
    _get_subnet_ids,
    _get_custom_actions,
    _get_root_volume_encrypted,
    _gdr_capable_types,
    _cluster_arch,
    _check_queue_arch_matches_cluster,
    _load_cluster_config,
    _write_cluster_config,
    _recovery_guidance,
    _make_yaml,
    _queue_config_path,
    COMPUTE_RESOURCE_SUFFIX,
    PCLUSTER_NAME_MAX_LENGTH,
    QUEUE_NAME_MAX_LENGTH,
)

SAMPLE_CONFIG = """\
Region: us-east-2
Image:
  Os: ubuntu2404
HeadNode:
  InstanceType: c8g.xlarge
  Networking:
    SubnetId: subnet-0abc123
  Ssh:
    KeyName: test-serial
  Iam:
    InstanceRole: arn:aws:iam::123456789012:role/test-role
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 5
  SlurmQueues:
    - Name: compute
      CapacityType: SPOT
      Networking:
        SubnetIds:
          - subnet-0abc123
      ComputeResources:
        - Name: compute-resource
          Instances:
            - InstanceType: c8g.2xlarge
          MinCount: 0
          MaxCount: 8

SharedStorage:
  - MountDir: /shared
    Name: ebs-shared
"""


class TestValidateQueueName:
    def test_valid_name(self):
        _validate_queue_name("compute-spot")

    def test_valid_short(self):
        _validate_queue_name("q1")

    def test_consecutive_hyphens(self):
        with pytest.raises(PClusterMakerError, match="consecutive hyphens"):
            _validate_queue_name("compute--spot")

    def test_trailing_hyphen(self):
        with pytest.raises(PClusterMakerError, match="invalid queue name"):
            _validate_queue_name("compute-")

    def test_uppercase(self):
        with pytest.raises(PClusterMakerError, match="invalid queue name"):
            _validate_queue_name("Compute")

    # QUEUE_NAME_MAX_LENGTH is 16, but the character-class regex independently
    # caps names at 25, so a 26-char name is rejected either way and proves
    # nothing about the length check. Exercise the boundary itself.
    def test_at_length_limit_accepted(self):
        _validate_queue_name("a" * QUEUE_NAME_MAX_LENGTH)

    def test_one_over_length_limit_rejected(self):
        with pytest.raises(PClusterMakerError, match="the limit is") as exc:
            _validate_queue_name("a" * (QUEUE_NAME_MAX_LENGTH + 1))
        assert "compute resource name" in str(exc.value)

    def test_too_long(self):
        with pytest.raises(PClusterMakerError, match="the limit is"):
            _validate_queue_name("a" * 26)

    def test_underscore_rejected(self):
        with pytest.raises(PClusterMakerError, match="invalid queue name"):
            _validate_queue_name("compute_spot")

    def test_default_is_reserved(self):
        """PCluster's NameValidator has an explicit `re.match("^default$", name)`
        rejection. Accepting it locally means the failure surfaces from
        update-cluster after the compute fleet is already stopped."""
        with pytest.raises(PClusterMakerError, match="reserved"):
            _validate_queue_name("default")

    def test_default_substring_still_allowed(self):
        _validate_queue_name("defaults")
        _validate_queue_name("my-default")

    def test_queue_name_ceiling_leaves_room_for_resource_suffix(self):
        """The derived compute resource name is queue_name + "-resource" and
        PCluster applies the same 25-char NameValidator to it. A queue name that
        passes but whose resource name does not is rejected at update time."""
        assert QUEUE_NAME_MAX_LENGTH == PCLUSTER_NAME_MAX_LENGTH - len(COMPUTE_RESOURCE_SUFFIX)
        longest = "a" * QUEUE_NAME_MAX_LENGTH
        _validate_queue_name(longest)
        assert len(longest + COMPUTE_RESOURCE_SUFFIX) <= PCLUSTER_NAME_MAX_LENGTH
        with pytest.raises(PClusterMakerError, match="compute resource"):
            _validate_queue_name("a" * (QUEUE_NAME_MAX_LENGTH + 1))

    def test_autogenerated_default_name_fits(self):
        """The auto-generated name is f"{queue_type}-{ts}"; with the old
        %Y%m%d-%H%M stamp "compute-20260725-1430" (21 chars) yielded a 30-char
        resource name and every auto-named queue failed at update time."""
        from datetime import datetime
        ts = datetime(2026, 7, 25, 14, 30).strftime("%m%d%H%M")
        for queue_type in ("compute", "gpu"):
            name = f"{queue_type}-{ts}"
            _validate_queue_name(name)
            assert len(name + COMPUTE_RESOURCE_SUFFIX) <= PCLUSTER_NAME_MAX_LENGTH


class TestRecoveryGuidance:
    def test_update_stage_offers_rollback_and_restart(self):
        out = _recovery_guidance("mycluster", "us-east-2", "/tmp/config.mycluster", "update")
        assert "RECOVERY REQUIRED" in out
        assert "has NOT been restarted" in out
        assert "/tmp/config.mycluster.bak" in out
        assert "START_REQUESTED" in out
        assert "update-cluster" in out

    def test_start_stage_offers_restart_only(self):
        out = _recovery_guidance("mycluster", "us-east-2", "/tmp/config.mycluster", "start")
        assert "START_REQUESTED" in out
        assert ".bak" not in out

    def test_guidance_names_the_cluster_and_region(self):
        out = _recovery_guidance("mycluster", "eu-west-1", "/tmp/c", "update")
        assert "mycluster" in out
        assert "eu-west-1" in out


class TestValidateInstanceTypes:
    def test_valid_compute_list(self):
        result = _validate_instance_types("c8g.2xlarge,c7g.2xlarge", require_gpu=False)
        assert isinstance(result, list)
        assert "c8g.2xlarge" in result
        assert "c7g.2xlarge" in result

    # These two are mirror images of each other: inverting the require_gpu
    # conditions in the validator leaves both green under a bare raises(),
    # because each still exits — just down the wrong branch with the wrong
    # advice. Pin the direction of the complaint.
    def test_gpu_rejected_for_compute(self):
        with pytest.raises(PClusterMakerError) as exc:
            _validate_instance_types("g5.2xlarge", require_gpu=False)
        assert "is a GPU instance but --gpu was not specified" in str(exc.value)

    def test_non_gpu_rejected_for_gpu(self):
        with pytest.raises(PClusterMakerError) as exc:
            _validate_instance_types("c5.2xlarge", require_gpu=True)
        assert "is not a GPU instance but --gpu was specified" in str(exc.value)

    def test_valid_gpu(self):
        result = _validate_instance_types("p3.2xlarge", require_gpu=True)
        assert isinstance(result, list)
        assert "p3.2xlarge" in result

    def test_mixed_arch_rejected(self):
        with pytest.raises(PClusterMakerError) as exc:
            _validate_instance_types("c5.2xlarge,c8g.2xlarge", require_gpu=False)
        msg = str(exc.value)
        assert "mixed CPU architectures" in msg
        # The two buckets must not be swapped: c8g is the ARM half.
        assert "ARM: ['c8g.2xlarge']" in msg
        assert "x86: ['c5.2xlarge']" in msg

    def test_unknown_instance_warns_not_aborts(self, capsys):
        result = _validate_instance_types("r99.99xlarge", require_gpu=False)
        assert isinstance(result, list)
        assert "r99.99xlarge" in result
        captured = capsys.readouterr()
        assert "WARNING" in captured.out

    def test_deduplication(self):
        result = _validate_instance_types("c8g.2xlarge,c8g.2xlarge", require_gpu=False)
        assert len(result) == 1

    def test_empty_raises(self):
        with pytest.raises(PClusterMakerError, match="no instance types provided"):
            _validate_instance_types("", require_gpu=False)

    def test_yaml_injection_payload_rejected(self):
        payload = (
            "c6g.xlarge\nIam:\n  AdditionalIamPolicies:\n"
            "    - Policy: arn:aws:iam::aws:policy/AdministratorAccess\n  Dummy:"
        )
        with pytest.raises(PClusterMakerError, match="not a valid EC2 instance type"):
            _validate_instance_types(payload, require_gpu=False)

    def test_colon_rejected(self):
        with pytest.raises(PClusterMakerError, match="not a valid EC2 instance type"):
            _validate_instance_types("c5.2xlarge:", require_gpu=False)

    def test_no_dot_rejected(self):
        with pytest.raises(PClusterMakerError, match="not a valid EC2 instance type"):
            _validate_instance_types("c5xlarge", require_gpu=False)

    def test_embedded_whitespace_rejected(self):
        with pytest.raises(PClusterMakerError, match="not a valid EC2 instance type"):
            _validate_instance_types("c5.2xlarge extra", require_gpu=False)

    def test_bare_metal_accepted(self):
        result = _validate_instance_types("c8g.metal", require_gpu=False)
        assert result == ["c8g.metal"]

    def test_hyphenated_metal_size_accepted(self):
        result = _validate_instance_types("c8g.metal-24xl", require_gpu=False)
        assert result == ["c8g.metal-24xl"]

    def test_all_catalog_metal_types_accepted(self):
        # Every metal-family instance type in the toolkit's own catalog must
        # validate — this is the exact class of real input an earlier,
        # narrower injection-hardening regex rejected.
        metal_types = [
            "c5.metal", "c5n.metal", "c6a.metal", "c6g.metal", "c6i.metal",
            "c7a.metal-48xl", "c7g.metal", "c7i.metal-24xl", "c7i.metal-48xl",
            "c8g.metal-24xl", "c8g.metal-48xl", "i3.metal", "i3en.metal",
            "i4i.metal", "m5.metal", "m5dn.metal", "m5zn.metal", "m6a.metal",
            "m6g.metal", "m6i.metal", "m7a.metal-48xl", "m7g.metal",
            "m7i.metal-24xl", "m7i.metal-48xl", "r5.metal", "r5dn.metal",
            "r6a.metal", "r6g.metal", "r6i.metal", "r7a.metal-48xl", "r7g.metal",
            "r7i.metal-24xl", "r7i.metal-48xl", "z1d.metal",
        ]
        for itype in metal_types:
            result = _validate_instance_types(itype, require_gpu=False)
            assert result == [itype], f"{itype} failed validation"

    def test_hyphenated_family_high_memory_types_accepted(self):
        # High Memory instances hyphenate the FAMILY, not the size
        # (u-6tb1.56xlarge) — the mirror-image case of metal-*'s hyphenated
        # size. A regex that only special-cased one side rejected the other.
        high_memory_types = [
            "u-6tb1.56xlarge", "u-9tb1.112xlarge", "u-12tb1.112xlarge",
            "u-18tb1.112xlarge", "u-24tb1.112xlarge",
        ]
        for itype in high_memory_types:
            result = _validate_instance_types(itype, require_gpu=False)
            assert result == [itype], f"{itype} failed validation"

    def test_entire_instance_catalog_accepted(self):
        # The regex must accept every single instance type the toolkit itself
        # considers valid, whatever hyphenation shape AWS uses for it. This
        # is the real invariant — enumerating specific hyphen positions
        # (metal-*, u-*tb1, or whatever AWS ships next) is the wrong strategy
        # and has already produced two rounds of asymmetric regressions.
        import pcluster_aux_data
        for itype in pcluster_aux_data.ec2_instances_full_list:
            require_gpu = pcluster_aux_data.is_gpu_instance(itype)
            result = _validate_instance_types(itype, require_gpu=require_gpu)
            assert result == [itype], f"{itype} failed validation"

    def test_trailing_hyphen_rejected(self):
        with pytest.raises(PClusterMakerError, match="not a valid EC2 instance type"):
            _validate_instance_types("c5.2xlarge-", require_gpu=False)


class TestGdrCapableTypes:
    def test_p4d_is_gdr_capable(self):
        assert _gdr_capable_types(["p4d.24xlarge"]) == ["p4d.24xlarge"]

    def test_p4de_is_gdr_capable(self):
        assert _gdr_capable_types(["p4de.24xlarge"]) == ["p4de.24xlarge"]

    def test_p5_is_gdr_capable(self):
        assert _gdr_capable_types(["p5.48xlarge"]) == ["p5.48xlarge"]

    def test_p3_is_not_gdr_capable(self):
        assert _gdr_capable_types(["p3.2xlarge"]) == []

    def test_non_gpu_type_is_not_gdr_capable(self):
        assert _gdr_capable_types(["c5.2xlarge"]) == []

    def test_mixed_list_returns_only_gdr_capable(self):
        result = _gdr_capable_types(["p3.2xlarge", "p4d.24xlarge", "g5.2xlarge"])
        assert result == ["p4d.24xlarge"]

    def test_empty_list_returns_empty(self):
        assert _gdr_capable_types([]) == []


class TestClusterArch:
    def test_uniform_arm_cluster(self):
        assert _cluster_arch(_make_yaml().load(SAMPLE_CONFIG)) == "arm64"

    def test_uniform_x86_cluster(self):
        cfg = _make_yaml().load(SAMPLE_CONFIG.replace("c8g.", "c5."))
        assert _cluster_arch(cfg) == "x86_64"

    def test_mixed_cluster_is_indeterminate(self):
        """A cluster that already mixes architectures cannot arbitrate a new
        queue, so report None and let the add through rather than blocking on a
        state this tool did not create."""
        cfg = _make_yaml().load(SAMPLE_CONFIG.replace("c8g.xlarge", "c5.xlarge"))
        assert _cluster_arch(cfg) is None

    def test_head_node_alone_determines_arch(self):
        cfg = _make_yaml().load(SAMPLE_CONFIG)
        cfg["Scheduling"]["SlurmQueues"] = []
        assert _cluster_arch(cfg) == "arm64"

    def test_queues_alone_determine_arch(self):
        cfg = _make_yaml().load(SAMPLE_CONFIG)
        del cfg["HeadNode"]["InstanceType"]
        assert _cluster_arch(cfg) == "arm64"

    def test_no_instance_types_returns_none(self):
        cfg = _make_yaml().load(SAMPLE_CONFIG)
        del cfg["HeadNode"]["InstanceType"]
        cfg["Scheduling"]["SlurmQueues"] = []
        assert _cluster_arch(cfg) is None

    def test_missing_sections_do_not_raise(self):
        assert _cluster_arch({}) is None
        assert _cluster_arch({"Scheduling": {"SlurmQueues": None}}) is None


class TestCheckQueueArchMatchesCluster:
    """make_pcluster.py hard-fails on mixed head/compute architecture at build
    time, but nothing re-checked it when adding a queue to a live cluster, so
    `add` could bolt a Graviton queue onto an x86 cluster. PCluster accepts that
    config; the breakage surfaces later and indirectly — one Os setting is
    architecture-specific, and head-node-built software (Spack, the benchmark
    suite, anything with -march=native) cannot execute on a foreign node."""

    def test_arm_queue_on_arm_cluster_is_allowed(self):
        cfg = _make_yaml().load(SAMPLE_CONFIG)
        _check_queue_arch_matches_cluster(cfg, ["c7g.4xlarge"])

    def test_x86_queue_on_x86_cluster_is_allowed(self):
        cfg = _make_yaml().load(SAMPLE_CONFIG.replace("c8g.", "c5."))
        _check_queue_arch_matches_cluster(cfg, ["c5.4xlarge"])

    def test_x86_queue_on_arm_cluster_is_rejected(self):
        cfg = _make_yaml().load(SAMPLE_CONFIG)
        with pytest.raises(PClusterMakerError) as exc:
            _check_queue_arch_matches_cluster(cfg, ["c5.4xlarge"])
        msg = str(exc.value)
        assert "does not match this cluster" in msg
        assert "arm64" in msg and "x86_64" in msg
        assert "c5.4xlarge" in msg, "the error must name the rejected instance types"

    def test_arm_queue_on_x86_cluster_is_rejected(self):
        cfg = _make_yaml().load(SAMPLE_CONFIG.replace("c8g.", "c5."))
        with pytest.raises(PClusterMakerError) as exc:
            _check_queue_arch_matches_cluster(cfg, ["c7g.4xlarge"])
        assert "does not match this cluster" in str(exc.value)

    def test_indeterminate_cluster_arch_does_not_block(self):
        cfg = _make_yaml().load(SAMPLE_CONFIG.replace("c8g.xlarge", "c5.xlarge"))
        _check_queue_arch_matches_cluster(cfg, ["c7g.4xlarge"])
        _check_queue_arch_matches_cluster(cfg, ["c5.4xlarge"])

    def test_gpu_queue_arch_is_checked_too(self):
        """g5g is the Graviton GPU family; g5 is x86. Adding g5 to an ARM
        cluster is the same mismatch as any CPU queue."""
        cfg = _make_yaml().load(SAMPLE_CONFIG)
        with pytest.raises(PClusterMakerError, match="does not match this cluster"):
            _check_queue_arch_matches_cluster(cfg, ["g5.2xlarge"])


class TestGetSubnetIds:
    def test_returns_first_queue_subnets(self):
        queues = [{"Name": "compute", "Networking": {"SubnetIds": ["subnet-cpu"]}}]
        assert _get_subnet_ids(queues, prefer_gpu=False) == ["subnet-cpu"]

    def test_prefer_gpu_returns_gpu_queue(self):
        queues = [
            {"Name": "gpu", "Networking": {"SubnetIds": ["subnet-gpu"]}},
            {"Name": "compute", "Networking": {"SubnetIds": ["subnet-cpu"]}},
        ]
        assert _get_subnet_ids(queues, prefer_gpu=True) == ["subnet-gpu"]

    def test_prefer_gpu_falls_back_to_compute(self):
        queues = [{"Name": "compute", "Networking": {"SubnetIds": ["subnet-cpu"]}}]
        assert _get_subnet_ids(queues, prefer_gpu=True) == ["subnet-cpu"]

    def test_empty_queues_raises(self):
        with pytest.raises(PClusterMakerError):
            _get_subnet_ids([], prefer_gpu=False)


class TestGetCustomActions:
    def test_returns_none_when_absent(self):
        queues = [{"Name": "compute", "Networking": {"SubnetIds": ["subnet-cpu"]}}]
        assert _get_custom_actions(queues) is None

    def test_returns_copy(self):
        original = {"OnNodeStart": {"Script": "s3://bucket/script.sh"}}
        queues = [{"Name": "compute", "CustomActions": original}]
        result = _get_custom_actions(queues)
        assert result == original
        assert result is not original


class TestGetRootVolumeEncrypted:
    def test_inherits_true_from_existing_queue(self):
        queues = [{
            "Name": "compute",
            "ComputeSettings": {"LocalStorage": {"RootVolume": {"Encrypted": True}}},
        }]
        assert _get_root_volume_encrypted(queues) is True

    def test_inherits_false_from_existing_queue(self):
        queues = [{
            "Name": "compute",
            "ComputeSettings": {"LocalStorage": {"RootVolume": {"Encrypted": False}}},
        }]
        assert _get_root_volume_encrypted(queues) is False

    def test_defaults_to_false_when_absent(self):
        queues = [{"Name": "compute", "ComputeSettings": {"LocalStorage": {"RootVolume": {}}}}]
        assert _get_root_volume_encrypted(queues) is False

    def test_defaults_to_false_for_empty_queues(self):
        assert _get_root_volume_encrypted([]) is False

    def test_checks_multiple_queues_for_first_explicit_value(self):
        queues = [
            {"Name": "no-root-volume-info", "ComputeSettings": {}},
            {"Name": "compute", "ComputeSettings": {"LocalStorage": {"RootVolume": {"Encrypted": True}}}},
        ]
        assert _get_root_volume_encrypted(queues) is True


class TestLoadClusterConfig:
    def test_loads_valid_config(self, tmp_path):
        cluster_name = "mycluster"
        config_dir = tmp_path / "active_clusters" / cluster_name
        config_dir.mkdir(parents=True)
        config_file = config_dir / f"config.{cluster_name}"
        config_file.write_text(SAMPLE_CONFIG)

        with patch("pcluster_core._queue_config_path", return_value=str(config_file)):
            config, path, etag = _load_cluster_config(
                cluster_name, str(tmp_path)
            )

        assert config["Region"] == "us-east-2"
        assert path.endswith(f"config.{cluster_name}")
        assert etag is None, "a locally-sourced config has no remote version"

    def test_missing_file_raises(self, tmp_path):
        with patch(
            "pcluster_core._queue_config_path",
            return_value=str(tmp_path / "active_clusters" / "noexist" / "config.noexist"),
        ):
            with pytest.raises(PClusterMakerError):
                _load_cluster_config("noexist", str(tmp_path))

    def test_invalid_cluster_name_raises(self):
        with pytest.raises(PClusterMakerError):
            _queue_config_path("../../etc", "/tmp")


class TestRoundTrip:
    def test_add_and_remove_queue_is_lossless(self, tmp_path):
        config_file = tmp_path / "config.mycluster"
        config_file.write_text(SAMPLE_CONFIG)

        yaml = _make_yaml()

        with open(str(config_file)) as fh:
            config = yaml.load(fh)

        new_queue = {
            "Name": "spot-extra",
            "CapacityType": "SPOT",
            "Networking": {"SubnetIds": ["subnet-0abc123"]},
            "ComputeResources": [
                {
                    "Name": "spot-extra-resource",
                    "Instances": [{"InstanceType": "c8g.4xlarge"}],
                    "MinCount": 0,
                    "MaxCount": 4,
                }
            ],
        }
        config["Scheduling"]["SlurmQueues"].append(new_queue)
        _write_cluster_config(str(config_file), config)

        with open(str(config_file)) as fh:
            config2 = yaml.load(fh)

        queues = config2["Scheduling"]["SlurmQueues"]
        config2["Scheduling"]["SlurmQueues"] = [q for q in queues if q["Name"] != "spot-extra"]
        _write_cluster_config(str(config_file), config2)

        final_text = config_file.read_text()
        assert final_text == SAMPLE_CONFIG

    def test_long_scalars_are_not_reflowed(self, tmp_path):
        """ruamel folds at 80 columns by default, so any long value containing
        spaces — a Tags value, a description, a multi-word comment — comes back
        as a multi-line continuation. That is a spurious diff on lines this tool
        never edited, and the fold changes the emitted scalar's whitespace."""
        long_value = (
            "Managed by ParallelClusterMaker for the mycluster HPC cluster "
            "owned by the research computing group in us-east-2"
        )
        assert len(long_value) > 80
        config_file = tmp_path / "config.mycluster"
        config_file.write_text(SAMPLE_CONFIG)

        yaml = _make_yaml()
        with open(str(config_file)) as fh:
            config = yaml.load(fh)
        config["Tags"] = [{"Key": "Purpose", "Value": long_value}]
        _write_cluster_config(str(config_file), config)

        text = config_file.read_text()
        assert long_value in text, "long scalar was folded across lines"

    def test_previous_config_is_backed_up(self, tmp_path):
        """This file is the only copy of a live cluster's configuration. A
        removal the operator wants back, or a rewrite that is valid YAML but
        wrong, is otherwise unrecoverable without a cluster rebuild."""
        config_file = tmp_path / "config.mycluster"
        config_file.write_text(SAMPLE_CONFIG)
        backup = tmp_path / "config.mycluster.bak"
        assert not backup.exists()

        yaml = _make_yaml()
        with open(str(config_file)) as fh:
            config = yaml.load(fh)
        config["Scheduling"]["SlurmQueues"] = [
            q for q in config["Scheduling"]["SlurmQueues"] if q["Name"] != "compute"
        ]
        _write_cluster_config(str(config_file), config)

        assert backup.exists()
        assert backup.read_text() == SAMPLE_CONFIG
        assert "compute" not in config_file.read_text()

    def test_backup_is_skipped_when_no_prior_config(self, tmp_path):
        config_file = tmp_path / "config.newcluster"
        yaml = _make_yaml()
        _write_cluster_config(str(config_file), yaml.load(SAMPLE_CONFIG))
        assert config_file.exists()
        assert not (tmp_path / "config.newcluster.bak").exists()


# ---------------------------------------------------------------------------
# manage_pcluster_queue.py CLI surface
#
# The module fires a venv guard at import time and pytest may not be running
# inside .venv, so parse the source instead of importing it.
# ---------------------------------------------------------------------------

import ast
import re

_QUEUE_CLI = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "manage_pcluster_queue.py"
)
_CORE_SRC = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src", "pcluster_core.py"
)


def _cli_source():
    with open(_QUEUE_CLI) as fh:
        return fh.read()


def _core_source():
    with open(_CORE_SRC) as fh:
        return fh.read()


def _declared_flags(source):
    """Every long/short option string passed to parser.add_argument()."""
    flags = set()
    for node in ast.walk(ast.parse(source)):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (isinstance(func, ast.Attribute) and func.attr == "add_argument"):
            continue
        for arg in node.args:
            if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                flags.add(arg.value)
    return flags


class TestQueueAddCallsTheArchGuard:
    def test_core_add_queue_checks_arch_before_writing_the_config(self):
        """The architecture guard is only useful if it runs before the
        edit is persisted -- _save_cluster_config now writes the live
        cluster's only config file and mirrors it to the shared store.

        manage_pcluster_queue.py's own _do_add no longer contains this logic
        -- it now delegates to core_add_queue in pcluster_core.py, which is
        where the ordering guarantee actually lives now."""
        fn = next(
            n for n in ast.walk(ast.parse(_core_source()))
            if isinstance(n, ast.FunctionDef) and n.name == "core_add_queue"
        )
        called = [
            n.func.id for n in ast.walk(fn)
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)
        ]
        assert "_check_queue_arch_matches_cluster" in called, (
            "core_add_queue does not call the architecture guard"
        )
        assert called.index("_check_queue_arch_matches_cluster") < called.index(
            "_save_cluster_config"
        ), "the arch guard must run before the config is rewritten"


class TestQueueCliFlagNames:
    def test_error_messages_name_only_real_flags(self):
        """The messages named `-E/--ec2_instance_type`, `--queue_name`, and
        `-T/--queue_type` — those are argparse `dest=` names, not flags. A user
        who copied the flag out of the error got "unrecognized arguments" on the
        retry."""
        source = _cli_source()
        declared = _declared_flags(source)
        assert declared, "no add_argument flags parsed out of manage_pcluster_queue.py"

        # Only this script's own diagnostics. Reminder text also prints real
        # `pcluster update-cluster` invocations, whose flags belong to that CLI.
        cited = set()
        for node in ast.walk(ast.parse(source)):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            is_error = (
                isinstance(func, ast.Attribute) and func.attr in ("exit", "error")
            ) or (isinstance(func, ast.Name) and func.id == "SystemExit")
            if not is_error:
                continue
            # Join each message's segments first: an f-string splits into
            # Constants around every {placeholder}, so filtering per-segment
            # would strip the "pcluster " context off a trailing " --region ".
            text = " ".join(
                arg.value for arg in ast.walk(node)
                if isinstance(arg, ast.Constant) and isinstance(arg.value, str)
            )
            # Some messages embed a `pcluster ...` command to run; those flags
            # belong to the ParallelCluster CLI, not to this script.
            if "pcluster " in text:
                continue
            cited.update(re.findall(r"--[a-z][a-z_0-9-]*", text))
        assert cited, "no flags cited in any error message — guard would be vacuous"

        bogus = sorted(f for f in cited if f not in declared)
        assert not bogus, (
            f"error/help text cites flags argparse does not accept: {bogus}\n"
            f"declared: {sorted(f for f in declared if f.startswith('--'))}"
        )

    def test_queue_type_is_required_only_for_add(self):
        """_do_remove never reads args.queue_type, but main() used to reject a
        remove without -T, forcing the user to state a queue type that has no
        effect on the operation."""
        source = _cli_source()
        tree = ast.parse(source)

        remove_fn = next(
            n for n in ast.walk(tree)
            if isinstance(n, ast.FunctionDef) and n.name == "_do_remove"
        )
        reads_type = any(
            isinstance(n, ast.Attribute) and n.attr == "queue_type"
            for n in ast.walk(remove_fn)
        )
        assert not reads_type, (
            "_do_remove now reads queue_type; if that is intentional, main() must "
            "require -T for remove again and this test should be updated"
        )

        guard = re.search(r"if args\.action[^\n]*not args\.queue_type", source)
        assert guard, "the -T/--type requirement guard is gone from main()"
        assert "remove" not in guard.group(0), (
            f"main() still requires -T for remove: {guard.group(0)!r}"
        )
