#!/usr/bin/env python3
#
################################################################################
# Name:         compress_logfiles.py
# Author:       Rodney Marable <rodney.marable@gmail.com>
# Created On:   April 20, 2018
# Last Changed: July 19, 2026
# Purpose:      Compress log files generated by Axb_random.py
#
# Usage:
# $ compress_logfiles.py [-h] --jobid JOBID --matrix-size MATRIX_SIZE
################################################################################

import time
start_time = time.time()

import argparse
import contextlib
import gzip
import os
import platform
import shutil
import subprocess
import sys

exec_node = platform.node()

parser = argparse.ArgumentParser(description='Compress log files generated by Axb_random.py')
parser.add_argument('--jobid', '-J', help='name of the job', required=True)
parser.add_argument('--matrix-size', '-M', help='set dimensions of the square matrix A', required=True, type=int)
parser.add_argument('--compression_type', '-C', help='set the file compression type (gzip or pigz)', required=False, default='gzip', choices=['gzip', 'pigz'])
parser.add_argument('--compression_processes', '-P', help='number of CPUs to use for compression', required=False, type=int, default=8)

args = parser.parse_args()
cluster_jobid        = args.jobid
matrix_size          = args.matrix_size
compression_type     = args.compression_type
compression_processes = args.compression_processes

start_fileproc_time = time.time()

_log_path = cluster_jobid + ".log"
if not os.path.isfile(_log_path):
    sys.exit(f"ERROR: log file not found: {_log_path}")
raw_log_size_bytes = os.path.getsize(_log_path)

print(f"+ Initiated log file compression with {compression_type} on "
      f"{time.strftime('%a %d %b %Y @ %H:%M:%S', time.localtime(start_fileproc_time))}")

if compression_type == "gzip":
    with open(cluster_jobid + '.log', 'rb') as f_in, \
         gzip.open(cluster_jobid + '.log.gz', 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)
    os.remove(cluster_jobid + '.log')
elif compression_type == "pigz":
    if shutil.which("pigz") is None:
        sys.exit("ERROR: pigz not found on PATH. Install pigz or use --compression_type gzip.")
    subprocess.run(["pigz", "-f", "--processes", str(compression_processes), cluster_jobid + '.log'],
                   check=True)

end_fileproc_time = time.time()

compressed_log_size_bytes = os.path.getsize(cluster_jobid + ".log.gz")
os.makedirs('logs', exist_ok=True)
shutil.move(cluster_jobid + '.log.gz',
            f'logs/{cluster_jobid}.{matrix_size}.log.gz')

elapsed_fileproc_time = round(end_fileproc_time - start_fileproc_time, 4)
print(f"+ Completed log file compression with {compression_type} on "
      f"{time.strftime('%a %d %b %Y @ %H:%M:%S', time.localtime(end_fileproc_time))}")

with open(cluster_jobid + ".time.csv", "w") as tcf:
    tcf.write(f"{raw_log_size_bytes},{compressed_log_size_bytes},{elapsed_fileproc_time}\n")

sys.exit(0)
