################################################################################
# Name:		cleanup_performance.sh
# Author:	Rodney Marable <rodney.marable@gmail.com>
# Created On:	February 7, 2018
# Last Updated:	May 11, 2018
# Purpose:	Cleanup data and log files generated by Rmarable_* scripts
################################################################################
#
#!/bin/sh

echo ""
echo "================================================================================"
echo "    This script will DESTROY *all* existing performance log and data files!"
echo "================================================================================"
echo ""
read -p '    Please type YES to confirm: ' confirm
if [[ $confirm == "YES" || $confirm == "yes" ]]
then
	for dir in csv logs plots sge_data sge_job_data summary summary_final archive_hashtest archive_fibonacci_hash
	do
		if [ -d $dir ]
		then
			echo ""
			echo "-------------------------"
			echo "Removing $dir..."
			echo "-------------------------"
			rm -rfv $dir
		fi
	done
	for file in job_Axb_random.o* job_Axb_random.[0-9]*.csv job_Axb_random.[0-9]*log job_Axb_random.[0-9]*log.gz [0-9]*.csv [0-9]*.log [0-9]*.log.gz job_hashtest.job[0-9]*.log* job_fibonacci_hashtest.job[0-9]*.log*
	do
		if [ -f $file ]
		then
			echo ""
			echo "--------------------------------------"
			echo "Removing $file..."
			echo "--------------------------------------"
			rm -rfv $file
		fi
	done
	echo ""
	echo "Finished cleaning up!"
	exit 0
else
	echo "*** CONFIRMATION ERROR ***"
	echo "Aborting..."
	exit 1
fi
